1. numpy 기초

In [3]:
import numpy as np
list = [1,2,3,4,5]

In [10]:
arr = np.array(list)
arr2 = np.array([[1,2,3],[4,5,6]])

In [11]:
arr.shape

(5,)

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2.size

6

In [14]:
arr2.dtype

dtype('int32')

In [15]:
arr2.ndim

2

In [17]:
#0으로 초기화
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
arr_full = np.full((5,5), 3)
arr_full

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [20]:
arr = np.arange(1, 51, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [21]:
arr = np.random.rand(2,3)
arr

array([[0.6099453 , 0.11533402, 0.69309204],
       [0.50158895, 0.89105588, 0.11583348]])

In [23]:
arr = np.random.randint(2, 10, size = (2,4))
arr

array([[4, 8, 5, 4],
       [9, 6, 9, 2]])

In [24]:
arr2 = np.random.randint(2, 10, size = (2,4))
arr2

array([[4, 5, 8, 5],
       [7, 4, 3, 8]])

In [25]:
arr + arr2

array([[ 8, 13, 13,  9],
       [16, 10, 12, 10]])

In [26]:
arr * arr2

array([[16, 40, 40, 20],
       [63, 24, 27, 16]])

3. 인덱싱과 슬라이싱

In [28]:
arr5 = np.array([[1,2,3],[4,5,6]])
arr5[0][2]

3

In [29]:
arr5[0,2]

3

In [31]:
arr5[0,0:3] = 99
arr5

array([[99, 99, 99],
       [ 4,  5,  6]])

In [36]:
rearr = np.arange(50).reshape(5,10)
rearr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
rearr[:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
height = np.random.randint(160, 188, size = (1,10))
height

array([[181, 180, 166, 178, 176, 163, 161, 176, 179, 172]])

In [41]:
weight = np.random.randint(50, 90, size = (1, 10))
weight

array([[89, 80, 53, 66, 53, 84, 88, 55, 59, 72]])

In [75]:
tmp = ""
tmp = str(height[0])+"\n"+str(weight[0])
tmp = tmp.replace('[','').replace(']','')
tmp = tmp.replace(" ", ",")
f = open("height_weight.txt", 'a')
f.write(tmp)
f.close()

print(tmp)

181,180,166,178,176,163,161,176,179,172
89,80,53,66,53,84,88,55,59,72


In [76]:
data = np.loadtxt("height_weight.txt", delimiter=",")
data

array([[181., 180., 166., 178., 176., 163., 161., 176., 179., 172.],
       [ 89.,  80.,  53.,  66.,  53.,  84.,  88.,  55.,  59.,  72.]])

In [81]:
data[1]/(data[0]/100)**2

array([27.16644791, 24.69135802, 19.23356075, 20.83070319, 17.11002066,
       31.61579284, 33.94930751, 17.75568182, 18.41390718, 24.33747972])